### ISSUE TITLE
Startup failure on OS X

### ISSUE THREAD

**Issue by elmar-hinz** [iogf/vy#10]
Error Msg:

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

A window pops up with a red blinking bar and the label `vy none`. It doesn't react to vim like input.

Installed like this:

```
pip install untwisted
pip install pygments
pip install jedi
pip install vy
```

```
> python --version
Python 2.7.10
```

```
> uname -a
Darwin Elmars-MBP 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
```

**Comment by iogf** [comment]
That is due to ibash.py plugin instantiating a bash process. that is not an error msg at all it is just notifying you that ibash.py opened a process that is not tied to a tty. do you access irc.freenode.org? the ibash.py module is responsible by sending commands to a bash process i haven't documented it yet but if you have a skype handle or if you access irc i could help you to interact with bash through vy. 
the support chan on freenode is #vy and my nick is tau there.

**Comment by iogf** [comment]
vy doesnt mimic vim key commands there is a different set of key commands for vy which are documented in the file INTRO.md altough you can make vy look like vim or emacs by changing the key events/creating new modes etc.

**Comment by iogf** [comment]
Vy performs all vim commands under a different set of key events. the set of keys that vy uses helps you to spare more time when programming/editting files, take a look at INTRO.md file.

**Comment by elmar-hinz** [comment]
Is there a simple switch to give me full vim behaviour? 

I don't like to learn new keys, only for to test an editor. If it is named after vi, it should speak vi in first place. Else people are rather confused.

**Comment by iogf** [comment]
i was a vim user some years ago, i didnt like the idea of learning vimscript to develop stuff for vim and i realized that there could be possible to have a better scheme for keys than the one that vim implements. vim doesn't implement the best scheme for keys because there are tons of historical reasons and backward compatibility with existing plugins. vy supports about 90% of vim features and it is just three year old. that is all due to python power. you don't need vy to look like vim in the keys scheme although you could make vy easily look like you want. that is what i have done i just picked up the best keys scheme that is suitable for me and i believe most people would agree with me. 
the INTRO.md file shows you how to get introduced to vy, step by step, if you go through INTRO.md and you find some key that you think it wouldn't spare you a lot of time then let me know that i'll hear your point and consider changing it for better.

**Comment by elmar-hinz** [comment]
Thank you. Short answer, there is no simple switch.
